package dev.jiaming.ai_interview.rag

import dev.jiaming.ai_interview.document.DocumentSourceType
import org.assertj.core.api.Assertions.assertThat
import org.flywaydb.core.Flyway
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import org.testcontainers.containers.PostgreSQLContainer
import org.testcontainers.utility.DockerImageName
import java.time.Duration
import java.time.Instant
import java.util.UUID

class RagDocumentIndexRepositoryIntegrationTests {
    @Test fun insertClaimCreatesIndexingRowAndConflictIsIgnored() { val identity = identity(); val first = UUID.randomUUID(); assertThat(repository.insertClaim(first, identity, BASE)).isTrue(); assertThat(repository.insertClaim(UUID.randomUUID(), identity, BASE)).isFalse(); val stored = repository.find(identity).orElseThrow(); assertThat(stored.indexId()).isEqualTo(first); assertThat(stored.status()).isEqualTo(RagDocumentIndexStatus.INDEXING); assertThat(stored.claimVersion()).isEqualTo(1L); assertThat(stored.documentCount()).isZero() }
    @Test fun findReturnsEmptyForUnknownIdentity() { assertThat(repository.find(identity())).isEmpty() }
    @Test fun touchReadyOnlyUpdatesMatchingReadyClaim() { val identity = identity(); val id = UUID.randomUUID(); repository.insertClaim(id, identity, BASE); repository.markReady(id, 1L, 3, BASE); val later = BASE.plus(Duration.ofMinutes(5)); assertThat(repository.touchReady(id, 1L, later)).isTrue(); assertThat(repository.find(identity).orElseThrow().lastUsedAt()).isEqualTo(later); assertThat(repository.touchReady(id, 2L, BASE.plus(Duration.ofMinutes(10)))).isFalse(); val indexing = UUID.randomUUID(); repository.insertClaim(indexing, identity(), BASE); assertThat(repository.touchReady(indexing, 1L, later)).isFalse() }
    @Test fun markReadyRequiresIndexingStatusAndMatchingClaim() { val identity = identity(); val id = UUID.randomUUID(); repository.insertClaim(id, identity, BASE); assertThat(repository.markReady(id, 2L, 5, BASE)).isFalse(); assertThat(repository.markReady(id, 1L, 5, BASE)).isTrue(); val ready = repository.find(identity).orElseThrow(); assertThat(ready.status()).isEqualTo(RagDocumentIndexStatus.READY); assertThat(ready.documentCount()).isEqualTo(5); assertThat(repository.markReady(id, 1L, 9, BASE)).isFalse() }
    @Test fun markFailedRecordsErrorOnlyWhileIndexing() { val identity = identity(); val id = UUID.randomUUID(); repository.insertClaim(id, identity, BASE); assertThat(repository.markFailed(id, 1L, "VECTOR_INDEX_FAILED", BASE)).isTrue(); assertThat(repository.find(identity).orElseThrow().status()).isEqualTo(RagDocumentIndexStatus.FAILED); assertThat(lastError(id)).isEqualTo("VECTOR_INDEX_FAILED"); assertThat(repository.markFailed(id, 1L, "AGAIN", BASE)).isFalse() }
    @Test fun takeOverReclaimsStaleIndexingButNotAFreshClaim() { val identity = identity(); val id = UUID.randomUUID(); repository.insertClaim(id, identity, BASE); val fresh = repository.find(identity).orElseThrow(); assertThat(repository.takeOver(fresh, BASE, BASE.minus(Duration.ofMinutes(1)), BASE.minus(Duration.ofMinutes(1)))).isFalse(); val now = BASE.plus(Duration.ofMinutes(20)); assertThat(repository.takeOver(fresh, now, now.minus(Duration.ofMinutes(10)), now.minus(Duration.ofMinutes(5)))).isTrue(); val reclaimed = repository.find(identity).orElseThrow(); assertThat(reclaimed.status()).isEqualTo(RagDocumentIndexStatus.INDEXING); assertThat(reclaimed.claimVersion()).isEqualTo(2L); assertThat(reclaimed.indexingStartedAt()).isEqualTo(now); assertThat(repository.takeOver(fresh, now, now.plus(Duration.ofHours(1)), now.plus(Duration.ofHours(1)))).isFalse() }
    @Test fun takeOverReclaimsFailedIndexPastRetryCutoff() { val identity = identity(); val id = UUID.randomUUID(); repository.insertClaim(id, identity, BASE); repository.markFailed(id, 1L, "VECTOR_INDEX_FAILED", BASE); val failed = repository.find(identity).orElseThrow(); assertThat(repository.takeOver(failed, BASE, BASE, BASE.minus(Duration.ofMinutes(1)))).isFalse(); val now = BASE.plus(Duration.ofMinutes(10)); assertThat(repository.takeOver(failed, now, now, now.minus(Duration.ofMinutes(1)))).isTrue(); val reclaimed = repository.find(identity).orElseThrow(); assertThat(reclaimed.status()).isEqualTo(RagDocumentIndexStatus.INDEXING); assertThat(reclaimed.claimVersion()).isEqualTo(2L) }
    @Test fun cleanupCandidatesReturnsStaleTerminalIndexesButNotFreshOnes() { val cutoff = BASE.minus(Duration.ofDays(7)); val deleting = BASE.minus(Duration.ofMinutes(10)); val staleReady = seedReady(OLD); val staleFailed = seedFailed(OLD); val freshReady = seedReady(BASE); val freshFailed = seedFailed(BASE); val candidates = repository.cleanupCandidates(cutoff, deleting, 100).map { it.indexId() }; assertThat(candidates).contains(staleReady, staleFailed).doesNotContain(freshReady, freshFailed) }
    @Test fun claimDeletingFencesByClaimVersionAndEligibility() { val cutoff = BASE.minus(Duration.ofDays(7)); val deleting = BASE.minus(Duration.ofMinutes(10)); val identity = identity(); seedReady(OLD, identity); val stale = repository.find(identity).orElseThrow(); val claimed = repository.claimDeleting(stale, cutoff, deleting, BASE); assertThat(claimed).isPresent(); assertThat(claimed.asLong).isEqualTo(stale.claimVersion() + 1); assertThat(repository.find(identity).orElseThrow().status()).isEqualTo(RagDocumentIndexStatus.DELETING); assertThat(repository.claimDeleting(stale, cutoff, deleting, BASE)).isEmpty(); val freshIdentity = identity(); seedReady(BASE, freshIdentity); assertThat(repository.claimDeleting(repository.find(freshIdentity).orElseThrow(), cutoff, deleting, BASE)).isEmpty() }
    @Test fun deleteClaimedRemovesRowOnlyWhenDeletingAndVersionMatches() { val identity = identity(); val id = seedReady(OLD, identity); val stale = repository.find(identity).orElseThrow(); val version = repository.claimDeleting(stale, BASE.minus(Duration.ofDays(7)), BASE.minus(Duration.ofMinutes(10)), BASE).orElseThrow(); repository.deleteClaimed(id, version - 1); assertThat(repository.find(identity)).isPresent(); repository.deleteClaimed(id, version); assertThat(repository.find(identity)).isEmpty() }
    @Test fun restoreDeleteFailureReturnsRowToFailed() { val identity = identity(); val id = seedReady(OLD, identity); val stale = repository.find(identity).orElseThrow(); val version = repository.claimDeleting(stale, BASE.minus(Duration.ofDays(7)), BASE.minus(Duration.ofMinutes(10)), BASE).orElseThrow(); repository.restoreDeleteFailure(id, version - 1, BASE); assertThat(repository.find(identity).orElseThrow().status()).isEqualTo(RagDocumentIndexStatus.DELETING); repository.restoreDeleteFailure(id, version, BASE); assertThat(repository.find(identity).orElseThrow().status()).isEqualTo(RagDocumentIndexStatus.FAILED); assertThat(lastError(id)).isEqualTo("VECTOR_DELETE_FAILED") }
    private fun seedReady(at: Instant) = seedReady(at, identity()); private fun seedReady(at: Instant, identity: RagDocumentIndexIdentity): UUID { val id = UUID.randomUUID(); repository.insertClaim(id, identity, at); repository.markReady(id, 1L, 1, at); return id }; private fun seedFailed(at: Instant): UUID { val id = UUID.randomUUID(); repository.insertClaim(id, identity(), at); repository.markFailed(id, 1L, "VECTOR_INDEX_FAILED", at); return id }
    private fun lastError(id: UUID): String = jdbcTemplate.queryForObject("SELECT last_error FROM ai_interview_app.rag_document_indexes WHERE index_id = ?", String::class.java, id)!!
    private fun identity() = RagDocumentIndexIdentity(DocumentSourceType.RESUME, UUID.randomUUID().toString().replace("-", ""), "gemini-embedding-001", 1_024, "section-block-v3")
    companion object { private val BASE = Instant.parse("2026-07-20T12:00:00Z"); private val OLD = BASE.minus(Duration.ofDays(10)); private val POSTGRES = PostgreSQLContainer(DockerImageName.parse("pgvector/pgvector:pg16").asCompatibleSubstituteFor("postgres")).withDatabaseName("ai_interview_rag_repository_test").withUsername("ai_interview").withPassword("ai_interview"); private lateinit var jdbcTemplate: JdbcTemplate; private lateinit var repository: RagDocumentIndexRepository; @BeforeAll @JvmStatic fun setUp() { POSTGRES.start(); val source = DriverManagerDataSource(POSTGRES.jdbcUrl, POSTGRES.username, POSTGRES.password); jdbcTemplate = JdbcTemplate(source); Flyway.configure().dataSource(source).locations("classpath:db/migration").load().migrate(); repository = RagDocumentIndexRepository(jdbcTemplate) }; @AfterAll @JvmStatic fun tearDown() { POSTGRES.stop() } }
}
