apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-interview
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AzkZzz04/ai-interview.git
    targetRevision: docker-kubernetes-gitops
    path: deploy/ai-interview
    helm:
      releaseName: ai-interview
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-interview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
