package dev.jiaming.ai_interview.jobs

enum class JobStage {
    QUEUED, READING_FILE, EXTRACTING_TEXT, NORMALIZING_TEXT, CHUNKING_TEXT,
    ASSESSING_RESUME, GENERATING_QUESTIONS, SPLITTING_EXPERIENCE, SCORING_ANSWER, COMPLETED
}
